apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-discovery
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP