{{- if .Values.issuers.letsEncryptDevWithCloudflareDns01.enabled }}

# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-dev-cluster-issuer
spec:
 acme:
   email: {{ .Values.issuers.letsEncryptDevWithCloudflareDns01.acmeEmail }}
   # We use the staging server here for testing to avoid hitting
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: letsencrypt-dev-cluster-issuer-pk
   # https://cert-manager.io/docs/configuration/acme/dns01/
   solvers:
     - #selector:
       # dnsZones:
       #   - 'example.com'
       dns01:
         cloudflare:
          email: {{ .Values.issuers.letsEncryptDevWithCloudflareDns01.cloudflare.email }}
          {{- if .Values.cloudflareCredentialsFromESO.enabled }}
          apiTokenSecretRef:
            name: cloudflare-credentials
            key: api-token
          {{- else }}
          apiTokenSecretRef:
            name: {{ .Values.issuers.letsEncryptDevWithCloudflareDns01.cloudflare.apiTokenSecretRef.name }}
            key: {{ .Values.issuers.letsEncryptDevWithCloudflareDns01.cloudflare.apiTokenSecretRef.key }}
          {{- end }}
{{- end }}