{{- if .Values.perconaMySQLDatabase.enabled }}
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: {{ include "price-buddy.fullname" . }}-cluster
spec:
  crVersion: 1.18.0
  secretsName: {{ include "price-buddy.fullname" . }}-cluster-secrets
  allowUnsafeConfigurations: true  # required for 1-node clusters
  pxc:
    size: 1
    # Need to change to the open source 
    image: percona/percona-xtradb-cluster:8.0.42-33.1
    autoRecovery: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
    podDisruptionBudget:
      minAvailable: 0
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]    
        storageClassName: {{ .Values.perconaMySQLDatabase.storageClass}}
        resources:
          requests:
            storage: {{ .Values.perconaMySQLDatabase.size }}
  users:
    - name: pricebuddyuser
      dbs:
      - pricebuddy
      grants:
        - ALL PRIVILEGES
      withGrantOption: true
  proxysql:
    enabled: false
  haproxy:
    enabled: false
  logcollector:
    enabled: false
  pmm:
    enabled: false
{{- end }}